### ISSUE TITLE
Fair-I-IPS vs. Fair-I-Pers

### ISSUE THREAD

**Issue by luhongyu** [MarcoMorik/Dynamic-Fairness#1]
Thanks for the great paper and experiments. 
I'm a little confused about the two versions of FairCo (-IPS and -Pers). 
According to my understanding, the differences between them are that -Pers use a updating neural LTR model to generate the rank while -IPS use the weighted popularity to generate the ranking. It should be quite different.
In section 8.2, the paper said FairCo is using the -Pers version, but in the code (main.py) the experiment 7/8/9 used the -IPS versions.

**Comment by MarcoMorik** [comment]
Hi,
Thank you very much for the comment. Indeed, -IPS is the unpersonalized and -Pers is the personalized version. 
The mistake in main.py must have happened while cleaning up the code. With -IPS, we do not generate the plots shown in the paper, as we really only shown the personalized FairCo for the news experiments. I fixed the bug, so the correct plots should be generated now.
